[package]
name = "tightbeam"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
bifrost = { path = "../bifrost/crates/bifrost" }
bifrost-iroh = { path = "../bifrost/crates/transports/bifrost-iroh" }
clap = { version = "4", features = ["derive"] }
eyre = "0.6"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
bifrost-mem = { path = "../bifrost/crates/transports/bifrost-mem" }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
wildcard_imports = "deny"
std_instead_of_core = "warn"

[lints.rust]
unused_must_use = "deny"
